<?php

namespace AppBundle\Repository;

/**
 * uzduotisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uzduotisRepository extends \Doctrine\ORM\EntityRepository
{
}
